# Generated by Django 4.2.7 on 2023-11-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=60)),
                ('service_title', models.CharField(max_length=100)),
                ('service_desc', models.TextField()),
            ],
        ),
    ]
