# Generated by Django 4.2.7 on 2023-11-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='service_desc',
            new_name='Notification_desc',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='service_icon',
            new_name='Notification_icon',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='service_title',
            new_name='Notification_title',
        ),
    ]
