# Generated by Django 4.2.7 on 2023-12-01 12:49

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_service_desc_notification_notification_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Notification_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Notification_title', unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_detailed_desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.FileField(default=None, max_length=300, upload_to='images/'),
        ),
    ]
