# Generated by Django 4.2.7 on 2023-12-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_notification_notification_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_detailed_desc',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=models.TextField(),
        ),
    ]
