# Generated by Django 4.2.7 on 2023-12-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_service_detailed_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_detailed_desc',
            field=models.TextField(default=None, null=True),
            preserve_default=False,
        ),
    ]
