# Generated by Django 4.2.7 on 2023-12-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_service_detailed_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_detailed_desc',
            field=models.TextField(default=None),
        ),
    ]
