# Generated by Django 4.2.7 on 2023-12-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_service_detailed_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_detailed_desc',
        ),
    ]
