# Generated by Django 4.2.7 on 2023-12-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_notification_notice_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='Notice_link',
        ),
        migrations.AlterField(
            model_name='notification',
            name='Notification_desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Notification_icon',
            field=models.CharField(max_length=60),
        ),
    ]
