# Generated by Django 4.2.7 on 2023-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_service_service_detailed_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Notice_link',
            field=models.URLField(default='', null=True),
        ),
    ]
