# Generated by Django 4.2.7 on 2023-12-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_service_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes_image', models.FileField(default=None, max_length=300, upload_to='images/')),
                ('Notes_title', models.CharField(max_length=200)),
                ('Notes_desc', models.TextField()),
                ('Notes_Download_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='Notification_desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Notification_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(max_length=200),
        ),
    ]
