# Generated by Django 4.2.7 on 2023-12-02 14:35

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_notesmodel_alter_notification_notification_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.URLField()),
                ('banner_image', models.ImageField(upload_to='youtube_banners/')),
                ('video_desc', models.TextField()),
                ('video_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Notification_title', unique=True)),
            ],
        ),
    ]
