# Generated by Django 4.2.7 on 2023-12-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_videosmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videosmodel',
            old_name='title',
            new_name='video_title',
        ),
    ]
